__001 넘파이 임포트__  
넘파이 모듈을 np라는 이름으로 임포트해보세요.

In [1]:
import numpy as np

__002 ndarray__  
리스트를 넘파이의 ndarray 객체로 변환해보세요.

```data = [1, 2, 3]```

In [2]:
data = [1, 2, 3]
np_data = np.array(data)
type(np_data)

numpy.ndarray

__003 arange__  
0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요.

In [3]:
np_data = np.arange(100)
type(np_data)

numpy.ndarray

__004 arange__  
구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요.
```
> arr
[ 3  6  9 12 15 18 21 24 27]
```

In [4]:
arr = np.arange(1, 10) * 3
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
arr = np.arange(3, 30, 3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

__005 arange__  
1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요.

In [6]:
arr = np.arange(2, 1000, 2)
arr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

__006 실수 range__  
0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.

In [7]:
arr = np.arange(0, 1, 0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

__007 reshape__  
리스트에는 6개의 데이터가 저장돼 있습니다.  
```data = [0, 1, 2, 3, 4, 5]```  
다음과 같이 2행 3열의 ndarray로 변환하세요.
```
[[0 1 2]
 [3 4 5]]
```

In [8]:
data = [0, 1, 2, 3, 4, 5]
arr = np.array(data)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

__008 reshape__  
다음의 2차원 ndarray 1차원 ndarray로 변환하세요.
```
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
```

In [9]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

arr.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

__009 reshape__  
주어진 ndarray를 다음과 같이 변경해 보세요.  
```arr = np.arange(3)```
```
[[0]
 [1]
 [2]]
```

In [10]:
arr = np.arange(3)
arr.reshape(1, 3)

array([[0, 1, 2]])

__010 에러의 원인__  
에러의 원인을 설명하세요.
```
> np.arange(6).reshape(2, 4)
ValueError: cannot reshape array of size 6 into shape (2,4)
```

In [11]:
# 6개의 데이터는 2 X 4 행렬 (8개의 데이터)에 비해 데이터 개수가 부족함.