In [1]:
import numpy as np

__011 2차원 배열__  
다음과 같이 2차원 ndarray 객체를 정의하세요.
```
[[0 1 2]
 [3 4 5]]
```

In [2]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

__012 ones__  
1이 20개 저장된 아래의 ndarray 객체를 만들어 보세요.  

```[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]```

In [3]:
arr = np.ones(20, dtype = int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

__013 ones__  
4행 5열로 저장된 아래의 ndarray 객체를 만들어 보세요.
```
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

In [4]:
arr = np.ones(20, dtype = int)
arr.reshape(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

__014 ones__  
255로 채워진 10X10 크기의 ndarray 객체를 생성하세요.

In [5]:
arr = np.ones(100, dtype = int) * 255
arr.reshape(10, 10)

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

__015 zeros__  
3x4 (행x열) 크기의 0으로 채워진 배열을 생생해보세요.

In [6]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

__016 dtype__  
[1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.

In [7]:
_list = [1, 2, 3]
arr = np.array(_list, dtype = np.int32)
type(arr.dtype)

numpy.dtype[int32]

__017 dtype__  
다음 배열의 데이터 타입을 확인해보세요.  
```arr = np.array([1, 2, 3])```


In [8]:
arr = np.array([1, 2, 3])
print(type(arr.dtype))
print(arr.dtype)

<class 'numpy.dtype[int32]'>
int32


__018 dtype__  
다음 배열의 데이터 타입을 확인해보세요.  
```arr = np.array(['1', '2', '3'])```

In [9]:
arr = np.array(['1', '2', '3'])
print(type(arr.dtype))
print(arr.dtype)

<class 'numpy.dtype[str_]'>
<U1


__019 dtype__  
다음 데이터를 np.int16 타입의 배열로 형변환하세요.  
```arr = np.array([1, 2, 3])```

In [10]:
arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

__020 데이터 타입__  
300이 44로 출력되는 이유를 설명하세요.
```
> a = np.array( [ 255, 300, 128], dtype=np.uint8 )
> a
[255  44 128]
```

`uint8`은 부호 없는 8비트 정수를 표현합니다. 0부터 255 (2^8 - 1) 범위의 수를 표현할 수 있습니다. 300은 `uint8`이 표현할 수 있는 범위를 넘기 때문에 잘못된 값이 출력됩니다.