In [1]:
import numpy as np

__031 ndarray 곱셈__  
전체 데이터에 10을 곱한 결과를 ndarray에 저장하세요.  
```data = [1, 2, 3]```

In [2]:
data = [1, 2, 3]

arr = np.array(data) * 10
print(arr)
arr.dtype

[10 20 30]


dtype('int32')

__032 ndarray 제곱__  
전체 데이터에 제곱한 결과를 ndarray에 저장하세요.  
```data = [1, 2, 3]```

In [3]:
data = [1, 2, 3]

arr = np.array(data) ** 2
print(arr)
arr.dtype

[1 4 9]


dtype('int32')

__033 ndarray 루트__  
전체 데이터에 루트를 적용한 결과를 ndarray에 저장하세요.  
```data = [1, 2, 3]```

In [4]:
data = [1, 2, 3]

arr = np.sqrt(data)
print(arr)

[1.         1.41421356 1.73205081]


__034 ndarray 컬럼 평균__  
다음 ndarray에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.
```
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
```
과목별 평균 점수를 출력하세요.
```
[12. 18.]
```

In [5]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

score.mean(axis = 0)

array([12., 18.])

__035 ndarray 로우 표준편차__  
다음 ndarray에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.
```
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
```
중간고사와 기말고사의 표준편차를 출력하세요.
```
[5. 1.]
```

In [6]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

score.std(axis = 1)

array([5., 1.])

__036 행렬곱__  
두 행렬의 곱셉결과를 출력하세요.
```
> a = np.arange(4).reshape(2,2)
> a
[[0 1]
 [2 3]]
> b = np.arange(1, 5).reshape(2,2)
> b
[[1 2]
 [3 4]]
```

In [7]:
a = np.arange(4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)

a@b

array([[ 3,  4],
       [11, 16]])

In [8]:
np.matmul(a, b)

array([[ 3,  4],
       [11, 16]])

__037 전치행렬__  
다음의 ndarray로 행과 열의 위치를 바꾼 전치행렬을 출력하세요.  
```arr = np.arange(9).reshape(3, 3)```

In [9]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print("\n",arr.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 3 6]
 [1 4 7]
 [2 5 8]]


__038 짝수 배열__  
다음 배열에서 짝수 값만 추출하세요.  
```arr = np.arange(10)```

In [10]:
arr = np.arange(10)
arr[::2]

array([0, 2, 4, 6, 8])

__039 홀수 배열__  
다음 배열에서 짝수 값만 추출하세요.  
```arr = np.arange(10)```

In [11]:
arr = np.arange(10)
arr[1::2]

array([1, 3, 5, 7, 9])

__040 여러 조건__  
다음 배열에서 3보다 크고 7보다 작은수만 추출하세요  
```arr = np.arange(10)```

In [12]:
arr = np.arange(10)
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])

In [13]:
arr[4:7]

array([4, 5, 6])