In [1]:
import numpy as np

__041 조건에 맞는 원소값 출력__  
다음 ndarray 객체에서 음수를 출력하세요.  
```arr = np.array([-1, 2, -3, 4])```

In [2]:
arr = np.array([-1, 2, -3, 4])
arr[arr < 0]

array([-1, -3])

__042 조건에 맞는 원소값 변경__  
다음 ndarray 객체에서 음수를 0으로 치환하세요.  
```arr = np.array([-1, 2, -3, 4])```

In [3]:
arr = np.array([-1, 2, -3, 4])
arr[arr < 0] = 0
arr

array([0, 2, 0, 4])

__043 조건에 맞는 원소값 변경__  
다음 ndarray 객체에서 음수를 양수로 변환하세요.  
```arr = np.array([-1, 2, -3, 4])```

In [4]:
arr[arr < 0] = -arr[arr < 0]
arr

array([0, 2, 0, 4])

In [5]:
arr = np.array([-1, 2, -3, 4])

__044 조건에 맞는 원소값 변경__  
다음 ndarray 객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 빼세요.  
```arr = np.array([-1, 2, -3, 4])```

In [6]:
arr = np.array([-1, 2, -3, 4])
arr[arr > 0] = arr[arr > 0] + 10
arr[arr < 0] = arr[arr < 0] - 10
arr

array([-11,  12, -13,  14])

In [7]:
arr = np.array([-1, 2, -3, 4])
np.where(arr > 0, arr + 10, arr - 10)

array([-11,  12, -13,  14])

__045 shuffle__  
numpy random 모듈의 shuffle 함수를 사용해서 입력 리스트의 원소들을 랜덤하게 섞어 보세요.  
```arr = [1, 2, 3, 4, 5]```

In [8]:
arr = [1, 2, 3, 4, 5]
np.random.shuffle(arr)
arr

[3, 4, 2, 1, 5]

__046 argmin__  
다음 넘파일 배열에서 최솟값의 인덱스를 출력하세요.  
```arr = np.array([1, 2, 3, 4, 5])```

In [9]:
arr = np.array([1, 2, 3, 4, 5])
np.min(arr)

1

__047 argmax__  
다음 넘파일 배열에서 최댓값의 인덱스를 출력하세요.  
```arr = np.array([1, 2, 3, 4, 5])```

In [10]:
arr = np.array([1, 2, 3, 4, 5])
np.max(arr)

5

__048 정렬__  
다음 넘파이 배열을 오름차순 정렬해보세요.  
```arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])```

In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

__049 numpy.vstack__  
numpy.vstack 함수를 사용하여 다음 2차원 배열을 생성하세요.  
```
array([[1, 2],
       [3, 4]])
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
```

In [12]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4]])

__050 flatten__  
flatten 메서드를 사용하여 다음 배열을 1차원 배열로 변경하세요.  
```arr = np.array([ [1, 2], [3, 4] ])```

In [13]:
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])